### ISSUE TITLE
Create backend code base - Express, mongoose, jwt

### ISSUE THREAD

**Issue by ngonhan2k5** [ngonhan2k5/mwa-final#3]
### A2. Create **backend** code base:
1. Specs:
   * using express-generator
   * mongoose, jwt auths
   * REST
   * dev env and prod env
2. Structure:  Structuring REST route see Feature [Tasks] (https://github.com/ngonhan2k5/mwa-final/issues/1)
   * common: signin, signup, ...
   * farmers: CRUD
   * customers: CRUD
   * orders: CRUD
   * products: CRUD

**Comment by ngonhan2k5** [comment]
@knguyen93 How about folder name convention? frontend vs backend?

**Comment by knguyen93** [comment]
> @knguyen93 How about folder name convention? frontend vs backend?

I refer frontend-app & backend-app
